### ISSUE TITLE
Parse 'end' day & time to calculate presentation & collection duration

### ISSUE THREAD

**Issue by brianflanagan** [civictech-ie/yourwaste-ie#3]
The CSV gives a start + end time for presentation and collection, but we'd like to store it in the database as a duration (in seconds).

**Comment by tewson** [comment]
@brianflanagan Is this for calculating time remaining between, say, now and next collection?

**Comment by brianflanagan** [comment]
The spreadsheet has a presentation/collection _start_ day and time, and _end_ day and time. But I think it'd make more sense to store it in the DB as I have it defined in the schema: day, start time, and duration. Something like `duration = end_time - start_time`.

**Comment by tewson** [comment]
@brianflanagan And this duration will be presented to the user in what way? I'm just trying to imaging what the duration is used for.

**Comment by brianflanagan** [comment]
Bags can be presented or collected between `time_start` and `time_end` – we'll show that to visitors on the streets#show page. Because sometimes/often that spans across two days, it's more straightforward to store a duration and calculate the `time_end` on the fly.

No time to work on this today, but can take a stab this week.
