### ISSUE TITLE
Hook up Google Sheets for easy content updating

### ISSUE THREAD

**Issue by brianflanagan** [civictech-ie/yourwaste-ie#5]
The data is currently seeded from a CSV file during the release phase. Why not pull the tabular data directly from Google Sheets?

**Comment by tewson** [comment]
@brianflanagan I created this branch to try out seeding from Google Sheets: https://github.com/civictech-ie/yourwaste-ie/commits/import-google-sheets-api

To try it, run
```
GOOGLE_API_KEY=<Google API key> bundle exec rake db:seed
```

Unless you already have an API key, I can share my API key via email.
